// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ie_w_efpKX29HyCBoDFjscm73fJftIg',
    appId: '1:255736834120:web:9451dc0ee88d751153507d',
    messagingSenderId: '255736834120',
    projectId: 'interview-demo-application',
    authDomain: 'interview-demo-application.firebaseapp.com',
    storageBucket: 'interview-demo-application.appspot.com',
    measurementId: 'G-NPL3XTELV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkXXIhhWGTZWk3p8kIxRIh9CosOhEX4q8',
    appId: '1:255736834120:android:1e9a6b6f79290ed053507d',
    messagingSenderId: '255736834120',
    projectId: 'interview-demo-application',
    storageBucket: 'interview-demo-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOzITrUo8ZGTn2ST8VBOwdovdK5csOP3c',
    appId: '1:255736834120:ios:a96525405129b6e453507d',
    messagingSenderId: '255736834120',
    projectId: 'interview-demo-application',
    storageBucket: 'interview-demo-application.appspot.com',
    iosClientId: '255736834120-7ouhoffd0r68ombco37bp31r1p6r72og.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewDemoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOzITrUo8ZGTn2ST8VBOwdovdK5csOP3c',
    appId: '1:255736834120:ios:a96525405129b6e453507d',
    messagingSenderId: '255736834120',
    projectId: 'interview-demo-application',
    storageBucket: 'interview-demo-application.appspot.com',
    iosClientId: '255736834120-7ouhoffd0r68ombco37bp31r1p6r72og.apps.googleusercontent.com',
    iosBundleId: 'com.example.interviewDemoApplication',
  );
}
